apiVersion: dns.gcp.upbound.io/v1beta1
kind: RecordSet
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/recordset
  labels:
    testing.upbound.io/example-name: frontend
  name: frontend
spec:
  forProvider:
    managedZone: ${google_dns_managed_zone.prod.name}
    name: frontend.${google_dns_managed_zone.prod.dns_name}
    rrdatas:
    - ${google_compute_instance.frontend.network_interface[0].access_config[0].nat_ip}
    ttl: 300
    type: A

---

