apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalForwardingRule
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/globalforwardingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    ipAddressSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    ipProtocol: TCP
    loadBalancingScheme: EXTERNAL
    portRange: "443"
    provider: ${google}
    targetSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalAddress
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/globalforwardingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider: {}

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/globalforwardingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    autoCreateSubnetworks: false
    provider: ${google}

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: SSLCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/globalforwardingrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    certificateSecretRef:
      key: attribute.cert_pem
      name: example-self-signed-cert
      namespace: upbound-system
    privateKeySecretRef:
      key: attribute.private_key_pem
      name: example-private-key
      namespace: upbound-system

---

