apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionTargetHTTPProxy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regiontargethttpproxy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: us-central1
    urlMapSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionURLMap
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regiontargethttpproxy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    defaultService: ${google_compute_region_backend_service.default.id}
    hostRule:
    - hosts:
      - mysite.com
      pathMatcher: allpaths
    pathMatcher:
    - defaultService: ${google_compute_region_backend_service.default.id}
      name: allpaths
      pathRule:
      - paths:
        - /*
        service: ${google_compute_region_backend_service.default.id}
    region: us-central1

---

