apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionTargetHTTPSProxy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regiontargethttpsproxy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: us-central1
    sslCertificatesRefs:
    - name: default
    urlMapSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionSSLCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regiontargethttpsproxy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    certificateSecretRef:
      key: attribute.certificate.crt
      name: example-secret
      namespace: upbound-system
    privateKeySecretRef:
      key: attribute.private.key
      name: example-secret
      namespace: upbound-system
    region: us-central1

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: RegionURLMap
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regiontargethttpsproxy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    defaultService: ${google_compute_region_backend_service.default.id}
    description: a description
    hostRule:
    - hosts:
      - mysite.com
      pathMatcher: allpaths
    pathMatcher:
    - defaultService: ${google_compute_region_backend_service.default.id}
      name: allpaths
      pathRule:
      - paths:
        - /*
        service: ${google_compute_region_backend_service.default.id}
    region: us-central1

---

