apiVersion: compute.gcp.upbound.io/v1beta1
kind: TargetHTTPSProxy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targethttpsproxy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    sslCertificatesRefs:
    - name: default
    urlMap: ${google_compute_url_map.default.id}

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: SSLCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targethttpsproxy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    certificateSecretRef:
      key: attribute.certificate.crt
      name: example-secret
      namespace: upbound-system
    privateKeySecretRef:
      key: attribute.private.key
      name: example-secret
      namespace: upbound-system

---

