apiVersion: compute.gcp.upbound.io/v1beta1
kind: TargetHTTPProxy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/targethttpproxy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    urlMap: ${google_compute_url_map.default.id}

---

